/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness, baseline store, collector diagnostics */
        get: {
            parameters: {
                query?: {
                    /** @description Pass `secrets` for a lightweight secret-backend reachability probe */
                    probe?: "secrets";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Health JSON */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            service?: string;
                            /** @description runtime_configuration = env/collector readiness only (no secret fetch). With ?probe=secrets, adds secret_backend_reachability and includes secrets_probe. */
                            diagnostics_scope?: string;
                            baseline_store?: unknown;
                            collector?: Record<string, never>;
                            secrets_probe?: Record<string, never> | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fleet/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fleet KPI snapshot including collector coverage */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Snapshot payload */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent audit entries (demo stub) */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    /** @description Case-insensitive substring match on audit action */
                    action?: string;
                    /** @description ISO-8601 timestamp — only events on or after this instant */
                    since?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tail of audit log */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: {
                                id?: string;
                                /** Format: date-time */
                                ts?: string;
                                action?: string;
                                detail?: string;
                                actor?: string | null;
                                scan_id?: string | null;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Append audit entry (demo stub) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        action: string;
                        detail: string;
                        actor?: string;
                        /** @description Optional correlation with scan jobs */
                        scan_id?: string;
                    };
                };
            };
            responses: {
                /** @description Record created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Audit-append rate limit */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List hosts in workspace */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    tag?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated hosts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["Host"][];
                            next_cursor?: string | null;
                        };
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/baselines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List captured baselines (summary per host) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            baselines?: {
                                hostId?: string;
                                hostname?: string;
                                /** Format: date-time */
                                capturedAt?: string;
                                listenersCount?: number;
                                usersCount?: number;
                                servicesCount?: number;
                            }[];
                        };
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Capture baselines for all configured collector hosts
         * @description Collects SSH snapshots from every COLLECTOR_HOST_N in parallel. Saves each successful baseline; partial failures are listed under `failed`. When a database is configured, the handler returns 202 and runs capture in the background so upstream proxies (e.g. Cloudflare) do not time out; poll GET /baselines/capture-jobs/{jobId} until `status` is succeeded or failed.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description At least one host captured successfully (legacy sync mode without DATABASE_URL) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            captured: {
                                hostId?: string;
                                hostname?: string;
                                /** Format: date-time */
                                capturedAt?: string;
                                listenersCount?: number;
                                usersCount?: number;
                                servicesCount?: number;
                                sudoers?: unknown;
                                cronEntries?: string[];
                                sshConfig?: unknown;
                                firewallActive?: boolean;
                            }[];
                            failed?: {
                                hostId?: string;
                                detail?: string;
                            }[];
                        };
                    };
                };
                /** @description Capture job accepted — poll capture-jobs for completion */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            job_id: string;
                            /** @enum {string} */
                            status: "queued";
                        };
                    };
                };
                /** @description Every host failed collection */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Collector not configured (missing COLLECTOR_HOST_1 or SSH_PRIVATE_KEY) */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/baselines/capture-jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll async baseline capture job status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Job state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            /** @enum {string} */
                            status?: "queued" | "running" | "succeeded" | "failed";
                            captured?: Record<string, never>[];
                            failed?: {
                                hostId?: string;
                                detail?: string;
                            }[];
                            error_detail?: string;
                            /** Format: date-time */
                            created_at?: string;
                            /** Format: date-time */
                            started_at?: string | null;
                            /** Format: date-time */
                            finished_at?: string | null;
                        };
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Job not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hosts/{hostId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get host detail and latest posture summary */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    hostId: components["parameters"]["hostId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HostDetail"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Host not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hosts/{hostId}/baselines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List baseline snapshots for a host */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    hostId: components["parameters"]["hostId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Baseline"][];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create baseline from latest successful scan */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    hostId: components["parameters"]["hostId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        label: string;
                        tags?: string[];
                        /** @description Optional scan to pin; default latest */
                        scan_id?: string;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Baseline"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden (trial_read_only or insufficient role) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hosts/{hostId}/drift": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List drift findings for host (latest scan vs active baseline) */
        get: {
            parameters: {
                query?: {
                    severity?: "high" | "medium" | "low";
                };
                header?: never;
                path: {
                    hostId: components["parameters"]["hostId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DriftFinding"][];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drift/{findingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get drift finding detail (evidence excerpts) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    findingId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DriftFinding"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Finding not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hosts/{hostId}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unified baseline vs current structured diff */
        get: {
            parameters: {
                query?: {
                    baseline_id?: string;
                    scan_id?: string;
                };
                header?: never;
                path: {
                    hostId: components["parameters"]["hostId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiffResult"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Host or baseline not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence/bundles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create evidence bundle export job */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        scope?: {
                            host_ids?: string[];
                            fleet_tags?: string[];
                        };
                        time_range?: {
                            /** Format: date-time */
                            from?: string;
                            /** Format: date-time */
                            to?: string;
                        };
                        include?: {
                            /** @default true */
                            findings_json?: boolean;
                            /** @default true */
                            summary_md?: boolean;
                            /** @default false */
                            config_excerpts?: boolean;
                        };
                        case_id?: string;
                        notes?: string;
                    };
                };
            };
            responses: {
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EvidenceBundleJob"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence/bundles/{bundleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get bundle job status or download URL when ready */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bundleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EvidenceBundleJob"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bundle not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/agent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push-agent snapshot ingest
         * @description The single endpoint the `blackglass-agent.sh` push agent (or any compatible CI agent) calls to stream a host bundle over HTTPS. This is the pull-model alternative used when a host sits in a strict VPC the Blackglass collector cannot reach via SSH.
         *     Authentication is Bearer with the tenant's INGEST_API_KEY (set in Settings → Collectors & ingest, or the `INGEST_API_KEY` env var on self-hosted instances). An optional INGEST_HOST_KEYS_JSON map can narrow each key to a single hostId for blast-radius reduction.
         *     Successful responses are also consumed by the wizard at `/onboarding`; the `summary` and `next` blocks drive the live bundle preview and the deep-link to the host detail page.
         *     Granular failure codes (`bundle_truncated`, `bundle_missing_sections`, `host_quota_exceeded`, `host_tombstoned`, `drift_pipeline_failed`, etc.) come back via the `{ error, detail, remedy }` envelope so the agent and wizard can render specific next-steps instead of generic 500s.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["HostSnapshot"];
                };
            };
            responses: {
                /** @description Snapshot accepted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            /**
                             * @description bootstrap_baseline on first push, ingest_ok thereafter
                             * @enum {string}
                             */
                            stage?: "bootstrap_baseline" | "ingest_ok";
                            hostId?: string;
                            /** Format: date-time */
                            capturedAt?: string;
                            bootstrap?: boolean;
                            driftEvents?: number;
                            summary?: {
                                sections?: number;
                                listeners?: number;
                                users?: number;
                                services?: number;
                            };
                            next?: {
                                /** Format: uri */
                                host_url?: string;
                                /** @enum {string} */
                                next_action?: "capture_baseline" | "review_findings";
                                /** Format: uri */
                                wizard_url?: string;
                            };
                        };
                    };
                };
                /** @description Validation failed, malformed bundle, or missing critical sections */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid Bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Tenant ingest scope, host allowance, or tombstone blocked the snapshot */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limit exceeded for this hostId */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Snapshot accepted locally but downstream drift pipeline failed */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description INGEST_API_KEY not configured on this instance */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List generated reports */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: {
                                id?: string;
                                title?: string;
                                /** @enum {string} */
                                format?: "markdown" | "pdf";
                                /** @enum {string} */
                                status?: "queued" | "running" | "ready" | "failed";
                                /** Format: date-time */
                                created_at?: string;
                            }[];
                            next_cursor?: string | null;
                        };
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Generate integrity report */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        title?: string;
                        fleet_tags?: string[];
                        /** @description ISO-8601 interval or preset */
                        period?: string;
                        /**
                         * @default pdf
                         * @enum {string}
                         */
                        format?: "markdown" | "pdf";
                    };
                };
            };
            responses: {
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            report_id?: string;
                            /** @enum {string} */
                            status?: "queued" | "running" | "ready" | "failed";
                        };
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent scan jobs */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["ScanJob"][];
                            next_cursor?: string | null;
                        };
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Enqueue a fleet drift scan */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Empty array triggers full-fleet scan */
                        host_ids?: string[];
                    };
                };
            };
            responses: {
                /** @description Scan job accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ScanJob"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden (trial_read_only or subscription_inactive) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limit exceeded (24 per minute per IP) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{scanId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get scan job status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scanId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ScanJob"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Scan job not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limit exceeded (320 polls per minute per IP) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drift": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all drift events across fleet (flat, paginated) */
        get: {
            parameters: {
                query?: {
                    /** @description Filter to a specific host */
                    hostId?: string;
                    lifecycle?: "new" | "triaged" | "accepted_risk" | "remediated" | "verified";
                    severity?: "high" | "medium" | "low";
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["DriftFinding"][];
                            total?: number;
                            next_cursor?: string | null;
                        };
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence/bundles/{bundleId}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download evidence bundle archive (binary) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bundleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Binary archive (.tar.gz or .zip) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bundle not found or not yet ready */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collector/keys/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the collector ingest API key for this tenant */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            rotated?: boolean;
                            message?: string;
                        };
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden — owner or admin role required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limit exceeded (5 per hour per IP) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a test webhook delivery to the configured endpoint */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            status_code?: number;
                            latency_ms?: number;
                        };
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limit exceeded (2 per minute per IP) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        HostSnapshot: {
            hostId: string;
            hostname: string;
            /** Format: date-time */
            collectedAt: string;
            listeners: {
                proto?: string;
                port?: number;
                bind?: string;
                process?: string | null;
            }[];
            users: {
                username?: string;
                uid?: number;
                gid?: number;
                shell?: string;
            }[];
            sudoers: {
                [key: string]: unknown;
            }[];
            cron: {
                [key: string]: unknown;
            }[];
            services: {
                [key: string]: unknown;
            }[];
            ssh: {
                [key: string]: unknown;
            };
            firewall: {
                [key: string]: unknown;
            };
        };
        Host: {
            id?: string;
            hostname?: string;
            os?: string;
            tags?: string[];
            /** Format: date-time */
            last_scan_at?: string | null;
            /** @enum {string} */
            trust_summary?: "aligned" | "drift" | "critical" | "unknown";
        };
        HostDetail: components["schemas"]["Host"] & {
            baseline_id?: string | null;
            category_counts?: {
                [key: string]: number;
            };
        };
        Baseline: {
            id?: string;
            host_id?: string;
            label?: string;
            /** Format: date-time */
            created_at?: string;
            scan_id?: string;
            tags?: string[];
        };
        ScanJob: {
            id?: string;
            /** @enum {string} */
            status?: "queued" | "running" | "succeeded" | "failed";
            host_ids?: string[];
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            /** @description Number of drift events found (real scans only) */
            drift_count?: number | null;
            /** @description Human-readable status message or error detail */
            detail?: string | null;
            error?: string | null;
        };
        DriftFinding: {
            id?: string;
            host_id?: string;
            scan_id?: string;
            /** @enum {string} */
            category?: "network_exposure" | "identity" | "persistence" | "ssh" | "firewall" | "packages";
            /** @enum {string} */
            severity?: "high" | "medium" | "low";
            /** @enum {string} */
            lifecycle?: "new" | "triaged" | "accepted_risk" | "remediated" | "verified";
            title?: string;
            rationale?: string;
            evidence?: {
                [key: string]: unknown;
            };
            /** @description JSON pointer / path in baseline snapshot */
            baseline_path?: string;
        };
        DiffResult: {
            host_id?: string;
            baseline_id?: string;
            scan_id?: string;
            changes?: {
                path?: string;
                rule_id?: string | null;
                severity?: string;
                summary?: string;
                before?: unknown;
                after?: unknown;
                before_sha256?: string | null;
                after_sha256?: string | null;
            }[];
        };
        EvidenceBundleJob: {
            id?: string;
            /** @enum {string} */
            status?: "queued" | "packaging" | "ready" | "failed";
            /** Format: uri */
            download_url?: string | null;
            sha256?: string | null;
            /** Format: date-time */
            expires_at?: string | null;
        };
    };
    responses: never;
    parameters: {
        hostId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
